# Global Settings
global:
  storageClass: "efs-sc"

# WordPress Configuration
wordpress:
  image:
    repository: wordpress
    tag: 6.4-apache
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    port: 80

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

  nodeSelector:
    subnet-type: public

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: subnet-type
                operator: In
                values:
                  - public

  persistence:
    enabled: true
    storageClass: "efs-sc"
    size: 10Gi
    accessMode: ReadWriteMany

# MySQL Configuration
mysql:
  enabled: true
  architecture: replication
  auth:
    existingSecret: mysql-secret
    rootPassword: "elmehdilafkaihi"           
    replicationPassword: "elmehdilafkaihi1"  
    password: "elmehdilafkaihi1"          
    database: wordpress
    username: wordpress
  primary:
    nodeSelector:
      subnet-type: private
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: subnet-type
                  operator: In
                  values:
                    - private
    persistence:
      enabled: true
      storageClass: "gp2"   # Use EBS StorageClass for MySQL
      size: 10Gi
  secondary:
    replicaCount: 1
    nodeSelector:
      subnet-type: private
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
                - key: subnet-type
                  operator: In
                  values:
                    - private
    persistence:
      enabled: true
      storageClass: "gp2"   # Use EBS StorageClass for MySQL
      size: 10Gi

# Storage Configuration
storage:
  efs:
    enabled: true
    fileSystemId: "fs-078a39d601f0ea2b2"  # Replace with your actual EFS File System ID
    provisioningMode: "efs-ap"
    directoryPerms: "777"
