apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-root-password: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
  mysql-password: {{ .Values.mysql.auth.password | b64enc | quote }}
  mysql-replication-password: {{ .Values.mysql.auth.replicationPassword | b64enc | quote }}
