apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: eu-west-3
  version: "1.27"

vpc:
  id: "<VPC_ID>"
  subnets:
    public:
      eu-west-3a:
        id: "<PUBLIC_SUBNET_ID>"
    private:
      eu-west-3a:
        id: "<PRIVATE_SUBNET_1_ID>"
      eu-west-3b:
        id: "<PRIVATE_SUBNET_2_ID>"

managedNodeGroups:
  - name: public-ng
    desiredCapacity: 2
    instanceType: t3.medium
    privateNetworking: false
    labels:
      subnet-type: public
      topology.kubernetes.io/zone: eu-west-3a
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
    ssh:
      publicKeyName: mykey
    iam:
      withAddonPolicies:
        efs: true
        albIngress: true
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/service-role/AmazonEFSCSIDriverPolicy

  - name: private-ng-1
    desiredCapacity: 2
    instanceType: t3.medium
    privateNetworking: true
    labels:
      subnet-type: private
      az: zone-1
      topology.kubernetes.io/zone: eu-west-3a
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
    ssh:
      publicKeyName: mykey

  - name: private-ng-2
    desiredCapacity: 2
    instanceType: t3.medium
    privateNetworking: true
    labels:
      subnet-type: private
      az: zone-2
      topology.kubernetes.io/zone: eu-west-3b
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
    ssh:
      publicKeyName: mykey
