apiVersion: v1
kind: Service
metadata:
  name: mysql-master
  labels:
    app: wordpress
    tier: mysql
    role: master
spec:
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    app: wordpress
    tier: mysql
    role: master
  clusterIP: None  # Headless service for StatefulSet
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-master-clusterip
  labels:
    app: wordpress
    tier: mysql
    role: master
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    app: wordpress
    tier: mysql
    role: master
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-slave
  labels:
    app: wordpress
    tier: mysql
    role: slave
spec:
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
  selector:
    app: wordpress
    tier: mysql
    role: slave
  clusterIP: None  # Headless service for StatefulSet
